#!/bin/sh
# vim: set ts=4:
#
# Ensures that Python 3.4+ and nodejs is available, installs modules specified
# in requirements.txt and package.json.
#
# Environment variables:
#   PYTHON : Python executable to use (default is python3 or python on PATH).
set -eu

cd "$(dirname "$0")/.."
. script/utils.sh

VENV_DIR="$(pwd)/.venv"


if [ "$(id -u)" -eq 0 ] && [ "$ALLOW_ROOT" != 'yes' ]; then
	die 'Do not run this script as root!'
fi

if [ ! -f "$VENV_DIR/bin/python3" ]; then
	einfo 'Initializing Python virtual environment...'

	# Find Python executable.
	for pybin in "${PYTHON:-}" python3 python NOT_FOUND; do
		has "$pybin" && break
	done
	if [ "$pybin" = 'NOT_FOUND' ]; then
		die 'Could not find python executable! Please install Python 3.4+.'
	fi

	if ! "$pybin" -c 'import sys; exit(not sys.version_info >= (3, 4, 0))'; then
		die "Python 3.4+ is required, but you have $("$pybin" -V 2>&1)!"
	fi

	# This can happen probably only on Debian-based distros.
	if ! "$pybin" -c 'import venv' 2>/dev/null; then
		die 'Python module venv is not installed!',
			'TIP: If you are using Debian-based distro, run "apt-get install python3-venv".'
	fi

	# This can happen probably only on Debian-based distros.
	if ! "$pybin" -c 'import pip' 2>/dev/null; then
		die 'Python module pip is not installed!',
			'TIP: If you are using Debian-based distro, run "apt-get install python3-pip".'
	fi

	"$pybin" -m venv "$VENV_DIR"
fi

. ./.envrc

einfo 'Installing Python modules...'
python3 -m pip install -r requirements-dev.txt 2>&1 \
	| sed -e '/^Requirement already satisfied/d' \
		-e '/don.t match your environment$/d'
